// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAie3X9zcxj3ivsTJ-fuRbTrgqwo-vIqSo',
    appId: '1:19539010998:web:8539ea35bd250fe4458d17',
    messagingSenderId: '19539010998',
    projectId: 'haven-c8c11',
    authDomain: 'haven-c8c11.firebaseapp.com',
    storageBucket: 'haven-c8c11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4A9htaV8VWSDck1KxHBh8PkX0wNTSFQg',
    appId: '1:19539010998:android:ce3f1aec9e8a747c458d17',
    messagingSenderId: '19539010998',
    projectId: 'haven-c8c11',
    storageBucket: 'haven-c8c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcr73aUDdQlZBU8g_URPmOvJgKid6RMx8',
    appId: '1:19539010998:ios:fb2ab079e12a684a458d17',
    messagingSenderId: '19539010998',
    projectId: 'haven-c8c11',
    storageBucket: 'haven-c8c11.firebasestorage.app',
    iosBundleId: 'com.example.paradiseView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcr73aUDdQlZBU8g_URPmOvJgKid6RMx8',
    appId: '1:19539010998:ios:fb2ab079e12a684a458d17',
    messagingSenderId: '19539010998',
    projectId: 'haven-c8c11',
    storageBucket: 'haven-c8c11.firebasestorage.app',
    iosBundleId: 'com.example.paradiseView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAie3X9zcxj3ivsTJ-fuRbTrgqwo-vIqSo',
    appId: '1:19539010998:web:417cb8c6a5d668e5458d17',
    messagingSenderId: '19539010998',
    projectId: 'haven-c8c11',
    authDomain: 'haven-c8c11.firebaseapp.com',
    storageBucket: 'haven-c8c11.firebasestorage.app',
  );
}
